### ISSUE TITLE
Functionality already in trifid-handler-fetch

### ISSUE THREAD

**Issue by cristianvasquez** [zazuko/trifid-handler-fs#2]
The functionality of this middleware is already covered by the [trifid-handler-fetch](https://github.com/zazuko/trifid-handler-fetch) middleware in the following way:

```yaml
middlewares:
  fetch-handler:
    module: trifid-handler-fetch
    config:
      url: file:../data/people.ttl
      contentType: application/n-triples
      split: true
      cache: true
```

Would it be a good idea to archive this one in favor of 'trifid-handler-fetch'?
